version: "3"
services:
  appwrite:
    type: web
    env: docker
    buildCommand: echo "Using Docker image"
    startCommand: docker run -d --restart always -p 80:80 -e _APP_DOMAIN=${_APP_DOMAIN} -e _DB_HOST=mariadb -e _DB_PORT=3306 -e _DB_USER=root -e _DB_PASSWORD=${_DB_PASSWORD} -e _REDIS_HOST=redis -e _REDIS_PORT=6379 appwrite/appwrite:0.15.3
    envVars:
      - key: _APP_DOMAIN
        value: ${_APP_DOMAIN}
      - key: _DB_HOST
        generateValue: mariadb
      - key: _DB_PORT
        value: "3306"
      - key: _DB_USER
        value: root
      - key: _DB_PASSWORD
        sync: false
      - key: _REDIS_HOST
        generateValue: redis
      - key: _REDIS_PORT
        value: "6379"

  mariadb:
    type: db
    env: docker
    buildCommand: echo "Using Docker image"
    startCommand: docker run -d --restart always -e MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} -e MYSQL_DATABASE=appwrite mariadb:10.5
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        value: appwrite

  redis:
    type: cache
    env: docker
    buildCommand: echo "Using Docker image"
    startCommand: docker run -d --restart always redis:6-alpine
